---
- name: Golden Standard Interface Configuration Deployment
  hosts: SOU-GW
  gather_facts: no
  vars:
    - webex_alert_msg: "Router Interface Configurations have been applied with golden standard."
  vars_files:
    - secrets.yml
  tasks:
    - name: Retrieve Gold Standard Interface Configuration
      ansible.builtin.include_vars:
        file: "../gold_standard/router_interface.yml"

    - name: Configure Interfaces
      cisco.ios.ios_config:
        lines:
          - "description '{{item.description}}'"
          - "ip address {{item.ip_address}} {{item.subnet_mask}}"
          - "bandwidth {{item.bandwidth}}"
          - "{{'shutdown' if item.shutdown else 'no shutdown'}}"
        parents:
          - "interface {{item.name}}"
      with_items: "{{interfaces}}"

    - name: Alert
      include_tasks: alert.yml
