---
- name: Config backup for switches
  hosts: all
  gather_facts: no
  tasks:
    - name: Get timestamp
      shell: "date +%Y%m%d-%H-%M-%S"
      register: timestamp

    - name: Ensure backup directory exists
      file:
        path: "data/{{ inventory_hostname }}"
        state: directory
        mode: '0755'

    - name: Backup routers config
      cisco.ios.ios_config: 
        backup: yes
        backup_options:
          filename: "running-config-{{ timestamp.stdout }}"
          dir_path: "data/{{ inventory_hostname }}"
      when: ansible_network_os == "cisco.ios.ios"
