---
- name: X
  hosts: SOU-GW
  gather_facts: no
  tasks:
    - name: Get ACL Information
      ansible.builtin.include_vars:
        file: "../gold_standard/router_acl.yml"

    - name: Configure Standard ACL
      cisco.ios.ios_config:
        lines:
          - "{{item}}"
      with_items: "{{acls.standard}}"

    - name: Configure Extended ACL
      cisco.ios.ios_config:
        lines:
          - "{{item}}"
        with_items: "{{acls.extended}}"
