---
- hosts: 127.0.0.1
  vars_prompt:
    - name: days
      prompt: How many days of configuration do you want to remove?
      private: false

  tasks:
    - name: Find files older than {{ days }} days
      ansible.builtin.find:
        paths: com615-awx-backups/backup/
        age: "{{ days }}d"
        file_type: file
        recurse: yes
      register: found_files

    - name: Remove all files older than {{ days }} days
      ansible.builtin.command:
        cmd: "rm {{ item.path }}"
      with_items: "{{ found_files.files }}"
