---
- name: "Get Running Configuration"
  hosts: SOU-GW
  # When we want to add additional list of hosts, we use : between
  # Example: SOU-GW:SOU-S:SOU-L
  gather_facts: no
  no_log: false
  collections:
    - lvrfrc87.git_acp

  tasks:
    - name: Timestamp
      ansible.builtin.shell: "date +%Y-%m-%d"
      register: timestamp

    - name: Group Name
      ansible.builtin.set_fact:
        group_name: "{{ group_names[0] }}"

    - name: Configuration Backup
      ios_config:
        backup: true
        backup_options:
          dir_path: ./com615-awx-backups/backup/{{ group_name }}/{{ inventory_hostname }}/
          filename: "{{ timestamp.stdout }}.cfg"

    - name: Fetch backup file to local machine
      ansible.builtin.fetch:
        src: /tmp/com615-awx-backups/backup/{{ group_name }}/{{ inventory_hostname }}/{{ timestamp.stdout }}.cfg
        dest: /home/workuser/CC/com615-awx-backups/backup/{{ group_name }}/{{ inventory_hostname }}/

- name: "Push to GitHub"
  hosts: localhost
  tasks:
    - name: Send to GitHub
      include_tasks: config_github.yml
